services:
  react_console:
    build:
      context: ./react-console
      dockerfile: Dockerfile
    ports:
      - "4300:80"
    volumes:
      - ./react-console/fleetbase.config.json:/usr/share/nginx/html/fleetbase.config.json
    restart: unless-stopped
