/**
 * Ember extension.js registry keys — React owner or explicit N/A (G053, §38).
 * Update when a registry key gains a React implementation.
 */
export const EXTENSION_REGISTRY_MANIFEST = {
  "engine:fleet-ops": { status: "partial", owner: "FleetOpsModuleLayout + App routes" },
  "fleet-ops:component:map:drawer": { status: "na", owner: "Deferred — map drawer plugin host" },
  "fleet-ops:component:vehicle:details": { status: "partial", owner: "VehicleDetail drawer" },
  "fleet-ops:component:driver:details": { status: "partial", owner: "DriverDetail drawer" },
  "fleet-ops:component:order-config-manager": { status: "done", owner: "OrderConfigManager" },
  "fleet-ops:component:order:details": { status: "partial", owner: "OrderDetail + detailRegistry extensions" },
  "fleet-ops:component:order:form": { status: "done", owner: "OrderForm" },
  "fleet-ops:component:order:form:payload:entity": { status: "partial", owner: "OrderForm entities + formRegistry order-payload-entity" },
  "fleet-ops:component:order:form:payload:entity:form": { status: "na", owner: "Inline entity rows — no separate Ember plugin surface" },
  "fleet-ops:component:contact:form": { status: "partial", owner: "SimpleEntityForm CRUD" },
  "fleet-ops:component:contact:form:details": { status: "na", owner: "CRUD fields only" },
  "fleet-ops:component:customer:form": { status: "done", owner: "CustomerDetail" },
  "fleet-ops:component:customer:form:details": { status: "na", owner: "Customer detail tabs" },
  "fleet-ops:component:driver:form": { status: "done", owner: "DriverForm" },
  "fleet-ops:component:driver:form:details": { status: "partial", owner: "formRegistry driver slot" },
  "fleet-ops:component:fleet:form": { status: "done", owner: "FleetForm" },
  "fleet-ops:component:fleet:form:details": { status: "partial", owner: "formRegistry fleet slot" },
  "fleet-ops:component:place:form": { status: "done", owner: "PlaceForm" },
  "fleet-ops:component:place:form:details": { status: "partial", owner: "formRegistry place slot" },
  "fleet-ops:component:vehicle:form": { status: "done", owner: "VehicleForm" },
  "fleet-ops:component:vehicle:form:details": { status: "partial", owner: "formRegistry vehicle slot" },
  "fleet-ops:component:vendor:form:create": { status: "partial", owner: "Vendor CRUD" },
  "fleet-ops:component:vendor:form:create:details": { status: "na", owner: "Vendor CRUD" },
  "fleet-ops:component:vendor:form:edit": { status: "partial", owner: "Vendor CRUD" },
  "fleet-ops:component:vendor:form:edit:details": { status: "na", owner: "Vendor CRUD" },
  "fleet-ops:component:issue:form": { status: "partial", owner: "Issue CRUD" },
  "fleet-ops:component:issue:form:details": { status: "na", owner: "Issue CRUD" },
  "fleet-ops:component:fuel-report:form": { status: "partial", owner: "Fuel report CRUD" },
  "fleet-ops:component:fuel-report:form:details": { status: "na", owner: "Fuel report CRUD" },
  "fleet-ops:component:maintenance:form": { status: "partial", owner: "Maintenance CRUD" },
  "fleet-ops:component:maintenance:form:details": { status: "na", owner: "Maintenance CRUD" },
  "fleet-ops:component:maintenance:details": { status: "partial", owner: "MaintenanceDetail" },
  "fleet-ops:component:work-order:form": { status: "partial", owner: "Work order CRUD" },
  "fleet-ops:component:work-order:form:details": { status: "na", owner: "Work order CRUD" },
  "fleet-ops:component:work-order:details": { status: "partial", owner: "WorkOrderDetail" },
  "fleet-ops:component:equipment:form": { status: "partial", owner: "Equipment CRUD" },
  "fleet-ops:component:equipment:form:details": { status: "na", owner: "Equipment CRUD" },
  "fleet-ops:component:equipment:details": { status: "partial", owner: "EquipmentDetail" },
  "fleet-ops:component:part:form": { status: "partial", owner: "Part CRUD" },
  "fleet-ops:component:part:form:details": { status: "na", owner: "Part CRUD" },
  "fleet-ops:component:part:details": { status: "partial", owner: "PartDetail" },
  "fleet-ops:contextmenu:vehicle": { status: "done", owner: "MapMarkerContextMenu + MapView" },
  "fleet-ops:contextmenu:driver": { status: "done", owner: "MapMarkerContextMenu + MapView" },
  "fleet-ops:template:settings:routing": { status: "done", owner: "RoutingSettingsPage" },
  "fleet-ops:template:settings:orchestrator": { status: "done", owner: "OrchestratorSettingsPage" },
};
