<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * Adds the missing operational columns to ledger_journals:
     *   - number:          Human-readable journal entry number (e.g. JE-0001)
     *   - type:            Entry type (general, payment, refund, adjustment, deposit, withdrawal, transfer, manual_entry)
     *   - status:          Entry status (posted, draft, voided)
     *   - reference:       External reference string (invoice number, order ID, etc.)
     *   - memo:            Short human-readable note on the entry
     *   - is_system_entry: Whether the entry was auto-generated by the system (true) or created manually (false)
     *
     * @return void
     */
    public function up()
    {
        Schema::table('ledger_journals', function (Blueprint $table) {
            $table->string('number')->nullable()->unique()->after('public_id');
            $table->string('type', 50)->nullable()->default('general')->index()->after('number');
            $table->string('status', 30)->nullable()->default('posted')->index()->after('type');
            $table->string('reference')->nullable()->after('status');
            $table->string('memo')->nullable()->after('reference');
            $table->boolean('is_system_entry')->default(false)->after('memo');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('ledger_journals', function (Blueprint $table) {
            $table->dropColumn(['number', 'type', 'status', 'reference', 'memo', 'is_system_entry']);
        });
    }
};
