/** Declarative order transition catalog — consumed by workflow engine. */

export const ORDER_TRANSITIONS = {
  dispatch: {
    id: "dispatch",
    label: "Dispatch",
    description: "Assign to field operations and notify the driver.",
    method: "dispatch",
    confirmTitle: "Dispatch order?",
    category: "workflow",
    from: ["created"],
    to: "dispatched",
  },
  start: {
    id: "start",
    label: "Start route",
    description: "Mark the order as en route.",
    method: "start",
    confirmTitle: "Start order?",
    category: "workflow",
    from: ["dispatched"],
    to: "en_route",
  },
  advance: {
    id: "advance",
    label: "Advance activity",
    description: "Move to the next step in the order flow.",
    method: "updateActivity",
    confirmTitle: "Advance workflow?",
    category: "workflow",
    requiresNextActivity: true,
    from: ["dispatched", "en_route", "arrived"],
  },
  complete: {
    id: "complete",
    label: "Complete",
    description: "Mark delivery as completed.",
    method: "complete",
    confirmTitle: "Complete order?",
    category: "workflow",
    from: ["en_route", "arrived", "delivered"],
    to: "completed",
  },
  cancel: {
    id: "cancel",
    label: "Cancel",
    description: "Cancel this order. This cannot be undone.",
    method: "cancel",
    confirmTitle: "Cancel order?",
    category: "workflow",
    destructive: true,
    from: ["created", "dispatched", "en_route", "arrived", "delayed"],
    to: "canceled",
  },
};
