/** Day 2 entity registry — shared list/detail/form configuration. */

export function mapCrudRow(raw = {}, fallbackPrefix = "entity") {
  const id = raw.uuid || raw.id || raw.public_id;
  return {
    id: String(id || ""),
    publicId: raw.public_id || raw.publicId || raw.internal_id || id || "—",
    name:
      raw.name ||
      raw.title ||
      raw.label ||
      raw.provider ||
      raw.policy_number ||
      raw.tracking_number ||
      raw.code ||
      raw.public_id ||
      "Untitled",
    status: raw.status || raw.state || "active",
    email: raw.email || "",
    phone: raw.phone || raw.phone_number || "",
    description: raw.description || raw.notes || "",
    type: raw.type || raw.category || "",
    raw,
  };
}

export const CRUD_ENTITIES = {
  vendor: {
    key: "vendor",
    pluralLabel: "Vendors",
    singularLabel: "Vendor",
    section: "Management",
    listPath: "/fleet-ops/management/vendors",
    permissionResource: "vendor",
    searchKeys: ["name", "publicId", "email", "phone"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "type", label: "Category / type" },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Phone" },
      { name: "status", label: "Status" },
      { name: "country", label: "Country" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  integratedVendor: {
    key: "integratedVendor",
    pluralLabel: "Integrated vendors",
    singularLabel: "Integrated vendor",
    section: "Management",
    listPath: "/fleet-ops/management/integrated-vendors",
    permissionResource: "vendor",
    searchKeys: ["name", "publicId"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "provider", label: "Provider", required: true },
      { name: "host", label: "Host / endpoint" },
      { name: "webhook_url", label: "Webhook URL" },
      { name: "status", label: "Status" },
      { name: "credentials", label: "Credentials (JSON)", type: "textarea" },
    ],
  },
  contact: {
    key: "contact",
    pluralLabel: "Contacts",
    singularLabel: "Contact",
    section: "Management",
    listPath: "/fleet-ops/management/contacts",
    permissionResource: "contact",
    searchKeys: ["name", "publicId", "email", "phone"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Phone" },
      { name: "title", label: "Title" },
      { name: "company_name", label: "Company" },
      { name: "customer_id", label: "Linked customer ID" },
      { name: "status", label: "Status" },
    ],
  },
  customer: {
    key: "customer",
    pluralLabel: "Customers",
    singularLabel: "Customer",
    section: "Management",
    listPath: "/fleet-ops/management/customers",
    permissionResource: "customer",
    searchKeys: ["name", "publicId", "email"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Phone" },
      { name: "contact_id", label: "Contact ID" },
    ],
  },
  fuelReport: {
    key: "fuelReport",
    pluralLabel: "Fuel reports",
    singularLabel: "Fuel report",
    section: "Management",
    listPath: "/fleet-ops/management/fuel-reports",
    permissionResource: "fuel-report",
    searchKeys: ["name", "publicId"],
    fields: [
      { name: "name", label: "Reference", required: true },
      { name: "vehicle_id", label: "Vehicle ID" },
      { name: "driver_id", label: "Driver ID" },
      { name: "volume", label: "Volume (L)" },
      { name: "cost", label: "Cost" },
      { name: "odometer", label: "Odometer (km)" },
      { name: "reported_at", label: "Reported at" },
      { name: "status", label: "Status" },
    ],
  },
  issue: {
    key: "issue",
    pluralLabel: "Issues",
    singularLabel: "Issue",
    section: "Management",
    listPath: "/fleet-ops/management/issues",
    permissionResource: "issue",
    searchKeys: ["name", "publicId", "status"],
    fields: [
      { name: "name", label: "Title", required: true },
      { name: "status", label: "Status" },
      { name: "priority", label: "Priority" },
      { name: "type", label: "Type" },
      { name: "vehicle_id", label: "Vehicle ID" },
      { name: "driver_id", label: "Driver ID" },
      { name: "order_id", label: "Order ID" },
      { name: "description", label: "Description", type: "textarea" },
    ],
    statusField: true,
  },
  telematic: {
    key: "telematic",
    pluralLabel: "Telematics",
    singularLabel: "Telematic",
    section: "Connectivity",
    listPath: "/fleet-ops/connectivity/telematics",
    permissionResource: "telematic",
    searchKeys: ["name", "publicId"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "provider", label: "Provider" },
      { name: "status", label: "Status" },
    ],
    readOnlyCreate: false,
  },
  device: {
    key: "device",
    pluralLabel: "Devices",
    singularLabel: "Device",
    section: "Connectivity",
    listPath: "/fleet-ops/connectivity/devices",
    permissionResource: "device",
    searchKeys: ["name", "publicId", "imei", "serial"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "imei", label: "IMEI" },
      { name: "serial", label: "Serial" },
      { name: "status", label: "Status" },
    ],
  },
  sensor: {
    key: "sensor",
    pluralLabel: "Sensors",
    singularLabel: "Sensor",
    section: "Connectivity",
    listPath: "/fleet-ops/connectivity/sensors",
    permissionResource: "sensor",
    searchKeys: ["name", "publicId", "type"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "type", label: "Type" },
      { name: "device_id", label: "Device ID" },
      { name: "geofence_id", label: "Geofence ID" },
      { name: "threshold", label: "Threshold" },
      { name: "unit", label: "Unit" },
      { name: "status", label: "Status" },
    ],
  },
  deviceEvent: {
    key: "deviceEvent",
    pluralLabel: "Device events",
    singularLabel: "Device event",
    section: "Connectivity",
    listPath: "/fleet-ops/connectivity/device-events",
    permissionResource: "device",
    searchKeys: ["name", "publicId", "type"],
    readOnly: true,
    fields: [],
  },
  maintenanceSchedule: {
    key: "maintenanceSchedule",
    pluralLabel: "Maintenance schedules",
    singularLabel: "Schedule",
    section: "Maintenance",
    listPath: "/fleet-ops/maintenance/schedules",
    permissionResource: "maintenance",
    searchKeys: ["name", "publicId"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "interval_km", label: "Interval (km)" },
      { name: "status", label: "Status" },
    ],
  },
  maintenance: {
    key: "maintenance",
    pluralLabel: "Maintenances",
    singularLabel: "Maintenance",
    section: "Maintenance",
    listPath: "/fleet-ops/maintenance/records",
    permissionResource: "maintenance",
    searchKeys: ["name", "publicId"],
    fields: [
      { name: "name", label: "Title", required: true },
      { name: "vehicle_id", label: "Vehicle ID" },
      { name: "status", label: "Status" },
    ],
  },
  workOrder: {
    key: "workOrder",
    pluralLabel: "Work orders",
    singularLabel: "Work order",
    section: "Maintenance",
    listPath: "/fleet-ops/maintenance/work-orders",
    permissionResource: "work-order",
    searchKeys: ["name", "publicId", "status"],
    fields: [
      { name: "name", label: "Title", required: true },
      { name: "vehicle_id", label: "Vehicle ID" },
      { name: "status", label: "Status" },
      { name: "description", label: "Description", type: "textarea" },
    ],
    statusField: true,
  },
  equipment: {
    key: "equipment",
    pluralLabel: "Equipment",
    singularLabel: "Equipment",
    section: "Maintenance",
    listPath: "/fleet-ops/maintenance/equipment",
    permissionResource: "equipment",
    searchKeys: ["name", "publicId"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "serial", label: "Serial" },
      { name: "vehicle_id", label: "Vehicle ID" },
      { name: "status", label: "Status" },
    ],
  },
  part: {
    key: "part",
    pluralLabel: "Parts",
    singularLabel: "Part",
    section: "Maintenance",
    listPath: "/fleet-ops/maintenance/parts",
    permissionResource: "part",
    searchKeys: ["name", "publicId", "sku"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "sku", label: "SKU" },
      { name: "quantity", label: "Quantity" },
      { name: "status", label: "Status" },
    ],
  },
  serviceArea: {
    key: "serviceArea",
    pluralLabel: "Service areas",
    singularLabel: "Service area",
    section: "Geo",
    listPath: "/fleet-ops/service-areas",
    permissionResource: "service-area",
    searchKeys: ["name", "publicId", "status"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "status", label: "Status" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  serviceAreaZone: {
    key: "serviceAreaZone",
    pluralLabel: "Service area zones",
    singularLabel: "Zone",
    section: "Geo",
    listPath: "/fleet-ops/service-areas",
    permissionResource: "service-area",
    searchKeys: ["name", "publicId", "status"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "status", label: "Status" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  customField: {
    key: "customField",
    pluralLabel: "Custom fields",
    singularLabel: "Custom field",
    section: "Platform",
    listPath: "/fleet-ops/custom-fields",
    permissionResource: "custom-field",
    searchKeys: ["name", "publicId", "status", "entity_type"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "entity_type", label: "Entity type", required: true },
      { name: "field_type", label: "Field type", required: true },
      { name: "status", label: "Status" },
    ],
  },
  warranty: {
    key: "warranty",
    pluralLabel: "Warranties",
    singularLabel: "Warranty",
    section: "Resources",
    listPath: "/fleet-ops/admin/warranties",
    permissionResource: "warranty",
    searchKeys: ["name", "publicId", "provider", "policy_number"],
    fields: [
      { name: "provider", label: "Provider", required: true },
      { name: "policy_number", label: "Policy number" },
      { name: "start_date", label: "Start date" },
      { name: "end_date", label: "End date" },
      { name: "coverage", label: "Coverage" },
      { name: "terms", label: "Terms", type: "textarea" },
      { name: "status", label: "Status" },
    ],
  },
  payload: {
    key: "payload",
    pluralLabel: "Payloads",
    singularLabel: "Payload",
    section: "Resources",
    listPath: "/fleet-ops/admin/payloads",
    permissionResource: "payload",
    searchKeys: ["name", "publicId", "type"],
    fields: [
      { name: "type", label: "Type" },
      { name: "payment_method", label: "Payment method" },
      { name: "cod_amount", label: "COD amount" },
      { name: "cod_currency", label: "COD currency" },
      { name: "pickup_uuid", label: "Pickup UUID" },
      { name: "dropoff_uuid", label: "Dropoff UUID" },
    ],
  },
  entity: {
    key: "entity",
    pluralLabel: "Entities",
    singularLabel: "Entity",
    section: "Resources",
    listPath: "/fleet-ops/admin/entities",
    permissionResource: "entity",
    searchKeys: ["name", "publicId", "type", "sku"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "type", label: "Type" },
      { name: "sku", label: "SKU" },
      { name: "weight", label: "Weight" },
      { name: "declared_value", label: "Declared value" },
      { name: "payload_uuid", label: "Payload UUID" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  proof: {
    key: "proof",
    pluralLabel: "Proofs",
    singularLabel: "Proof",
    section: "Resources",
    listPath: "/fleet-ops/admin/proofs",
    permissionResource: "proof",
    searchKeys: ["name", "publicId", "order_uuid"],
    fields: [
      { name: "order_uuid", label: "Order UUID" },
      { name: "subject_type", label: "Subject type" },
      { name: "subject_uuid", label: "Subject UUID" },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
  },
  purchaseRate: {
    key: "purchaseRate",
    pluralLabel: "Purchase rates",
    singularLabel: "Purchase rate",
    section: "Resources",
    listPath: "/fleet-ops/admin/purchase-rates",
    permissionResource: "purchase-rate",
    searchKeys: ["name", "publicId", "status"],
    fields: [
      { name: "status", label: "Status" },
      { name: "customer_uuid", label: "Customer UUID" },
      { name: "payload_uuid", label: "Payload UUID" },
      { name: "service_quote_uuid", label: "Service quote UUID" },
    ],
  },
  trackingNumber: {
    key: "trackingNumber",
    pluralLabel: "Tracking numbers",
    singularLabel: "Tracking number",
    section: "Resources",
    listPath: "/fleet-ops/admin/tracking-numbers",
    permissionResource: "tracking-number",
    searchKeys: ["name", "publicId", "tracking_number"],
    fields: [
      { name: "tracking_number", label: "Tracking number", required: true },
      { name: "region", label: "Region" },
      { name: "owner_type", label: "Owner type" },
      { name: "owner_uuid", label: "Owner UUID" },
      { name: "status_uuid", label: "Status UUID" },
    ],
  },
  trackingStatus: {
    key: "trackingStatus",
    pluralLabel: "Tracking statuses",
    singularLabel: "Tracking status",
    section: "Resources",
    listPath: "/fleet-ops/admin/tracking-statuses",
    permissionResource: "tracking-status",
    searchKeys: ["name", "publicId", "code"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "code", label: "Code" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
};
