/** Parking console sidebar routes → PMS permission slugs. */
export const PARKING_SIDEBAR_PERMISSIONS = {
  "/parking/admin/dashboard": "dashboard.view",
  "/parking/admin/users": "users.manage",
  "/parking/admin/pricing": "pricing.configure",
  "/parking/admin/parking": "parking.manage",
  "/parking/admin/parking-floors": "floors.manage",
  "/parking/admin/reports": "reports.admin",
  "/parking/admin/hardware": "hardware.configure",
  "/parking/admin/qr-monitoring": "qr.monitoring",
  "/parking/admin/audit-logs": "audit.view",
  "/parking/admin/settings": "settings.manage",
  "/parking/supervisor/dashboard": "dashboard.view",
  "/parking/supervisor/monitoring": "parking.status.view",
  "/parking/supervisor/parking-floors": "floors.monitor",
  "/parking/supervisor/vehicle-search": "vehicle.search",
  "/parking/supervisor/qr-monitoring": "qr.monitoring",
  "/parking/supervisor/reports": "reports.view",
  "/parking/supervisor/operator-activity": "operator.activity",
  "/parking/supervisor/recent-tickets": "recent.tickets",
  "/parking/operator/dashboard": "dashboard.view",
  "/parking/operator/occupancy": "floors.summary",
  "/parking/operator/new-ticket": "tickets.create",
  "/parking/operator/collect-payment": "payments.collect",
  "/parking/operator/qr-print": "qr.print",
  "/parking/operator/vehicle-search": "vehicle.search",
  "/parking/operator/recent-tickets": "recent.tickets",
  "/parking/operator/settings": "settings.manage",
};
